stages:
  - build
  - deploy

variables:
  SSH_KEY_PATH: "~/.ssh/id_rsa" # SSH 키 경로

build:
  stage: build
  image: node:16
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  before_script:
    - apt-get update -y
    - apt-get install -y rsync openssh-client
    - mkdir -p ~/.ssh
    - echo "$DEPLOY_KEY" > $SSH_KEY_PATH
    - chmod 600 $SSH_KEY_PATH
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  script:
    - rsync -avz -e "ssh -i $SSH_KEY_PATH" ./build/ $EC2_SERVER_ADDRESS:/var/www/html/
  only:
    - main